ecims/ecims/Controllers/TimelineController.cs
using ecims.Models;
using ecims.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ecims.Controllers
{
    public class TimelineController : Controller
    {
        ApplicationDbContext _context;
        private ApplicationUserManager _userManager;
        AuditTrailGenerator.AuditTrail _auditTrail = new AuditTrailGenerator.AuditTrail();

        public TimelineController()
        {
            _context = new ApplicationDbContext();

        }
        // GET: Timeline
        public ActionResult Index()
        {
            return View();
        }
        //Track application view
        [Authorize]
        [HttpGet]
        public ActionResult ApplicationTimeline()
        {
            //Get ID of the currently logged in user
            var userId = User.Identity.GetUserId();
            //Create user object based off user ID
            var user = _context.Users.Where(u => u.Id == userId).Single();

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            return View(new SearchCertificateViewModel
            {
                user = user,
                role = roles
            });
        }
        [Authorize]
        [HttpPost]
        public ActionResult ApplicationTimeline(SearchCertificateViewModel model)
        {
            //Get ID of the currently logged in user
            var userId = User.Identity.GetUserId();
            //Create user object based off user ID
            var user = _context.Users.Where(u => u.Id == userId).Single();

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            var ApplicationNumber = model.ApplicationNumber;

            //Retrieve the application in question
            var Application = _context.EndUserCertificate.Include(app => app.User).Where(app => app.applicationNo.Contains(ApplicationNumber)).FirstOrDefault();

            //List of agencies to match IDs against
            var AgencyList = _context.PortalSubCategories.ToList();

            //Return all workflow entries as long as the application number is valid
            if (!string.IsNullOrEmpty(ApplicationNumber))
            {
                var applicationWorkflow = _context.EUCWorkFlow
                                            .Include(app => app.Source)
                                            .Include(app => app.Source.PortalUserCategory)
                                            .Include(app => app.PortalCat)
                                            .Include(app => app.UserAgency)
                                            .Where(app => app.applicationNumber.Contains(ApplicationNumber)).ToList();

                return View(new SearchCertificateViewModel
                {
                    user = user,
                    role = roles,
                    Workflow = applicationWorkflow,
                    Application = Application,
                    ApplicationNumber = ApplicationNumber,
                    AgencyList = AgencyList
                });
            }
            else
            {
                TempData["Error"] = "Please enter a valid application number";
                //var eucAppList = _context.EUCWorkFlow.Where(e => e.applicationNumber == eucappNo).ToList();
                return View(new SearchCertificateViewModel
                {
                    user = user,
                    role = roles
                });
            }
        }
        //Track application view
        [Authorize]
        [HttpGet]
        public ActionResult CertificateTimeline()
        {
            //Get ID of the currently logged in user
            var userId = User.Identity.GetUserId();
            //Create user object based off user ID
            var user = _context.Users.Where(u => u.Id == userId).Single();

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            return View(new SearchCertificateViewModel
            {
                user = user,
                role = roles
            });
        }
        [Authorize]
        [HttpPost]
        public ActionResult CertificateTimeline(SearchCertificateViewModel model)
        {
            //Get ID of the currently logged in user
            var userId = User.Identity.GetUserId();
            //Create user object based off user ID
            var user = _context.Users.Where(u => u.Id == userId).Single();

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            var CertificateNumber = model.CertificateNumber;

            var Cert = _context.EUCCertificates.Where(cert => cert.CertNo == model.CertificateNumber).FirstOrDefault();
            //Retrieve the application in question
            var EndUserCertificate = _context.CertificateWorkflow.Include(app => app.User).Include(app => app.Certificate).Where(app => app.Certificate.CertNo == CertificateNumber).FirstOrDefault();

            //Return all workflow entries as long as the certificate number is valid
            if (!string.IsNullOrEmpty(CertificateNumber))
            {
                var certificateWorkflow = _context.CertificateWorkflow.Include(app => app.User).Where(app => app.Certificate.CertNo == CertificateNumber).ToList();

                //Get Application associated with this certificate
                var Application = _context.EndUserCertificate.Where(app => app.applicationNo == Cert.applicationNo).FirstOrDefault();

                return View(new SearchCertificateViewModel
                {
                    user = user,
                    role = roles,
                    CertificateWorkflow = certificateWorkflow,
                    CertificateNumber = CertificateNumber,
                    EndUserCertificate = Cert,
                    Application = Application
                });
            }
            else
            {
                TempData["Error"] = "Please enter a valid certificate number";
                //var eucAppList = _context.EUCWorkFlow.Where(e => e.applicationNumber == eucappNo).ToList();
                return View(new SearchCertificateViewModel
                {
                    user = user,
                    role = roles
                });
            }
        }
    }
}

ecims/ecims/Views/Timeline/CertificateTimeline.cshtml
@model ecims.ViewModels.SearchCertificateViewModel
@{
    ViewBag.Title = "Certificate Timeline";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}
<div class="row" style="margin:20px;">
    <div class="col-md-12 col-lg-12 col-sm-12">
        <div class="col-md-12 col-sm-12">
            <div class="content-panel" style="padding:20px;">
                <h4 style="font-weight:bold;">Certificate Timeline</h4>
                @if (TempData["Error"] != null)
                {
                    <div class="alert alert-danger" role="alert">
                        @TempData["Error"].ToString()
                    </div>
                }
                <div class="panel-body" style="border:solid; border-width:3px; border-radius: 4px 4px; border-color:#F2F2F2;">
                    <div class="table-responsive">
                        @using (Html.BeginForm("CertificateTimeline", "Timeline", FormMethod.Post))
                        {
                            <div class="col-md-12">

                                <div class="col-md-6">
                                    @Html.TextBoxFor(m => m.CertificateNumber, new { @class = "form-control", placeholder = "Enter the certificate number here...", required = "required" })
                                </div>
                                <div class="col-md-6" style="padding-left: 0px;">
                                    <input type="submit" class="btn btn-success" onclick="return checkTextField();" id="btnSubmit" value="Search" />
                                </div>
                            </div>
                            <hr />
                            if (Model.CertificateWorkflow != null)
                            {
                                <div class="container">
                                    <div class="page-header">
                                        <h3 id="">Certificate Number: @Model.EndUserCertificate.CertNo</h3>
                                        @Html.ActionLink("View Application Details", "EUCApplicationDetails", "Admin", new { appID = Model.Application.applicationNo, ID = Model.Application.id }, new { @class = "btn btn-success" })
                                    </div>
                                    @if (Model.CertificateWorkflow.Count == 0)
                                    {
                                    <div class="container">
                                        <div class="page-header">
                                            <h4 id="">No actions have been carried out on this certificate...</h4>
                                            <h4 id="">Certificate Number: @Model.EndUserCertificate.CertNo</h4>
                                        </div>
                                    </div>
                                    }
                                    <div class="col-md-12" id="timeline">
                                        <div class="row timeline-movement timeline-movement-top">
                                            <div class="timeline-badge timeline-future-movement">
                                                <a href="#">
                                                    <span class="glyphicon glyphicon-plus"></span>
                                                </a>
                                            </div>
                                            <div class="timeline-badge timeline-filter-movement">
                                                <a href="#">
                                                    <span class="glyphicon glyphicon-time"></span>
                                                </a>
                                            </div>
                                        </div>
                                        @{
                                            int i = 1;
                                            foreach (var item in Model.CertificateWorkflow)
                                            {
                                                int j = i % 2;
                                                string offset;
                                                string offset2;
                                                string alignment;
                                                if (j == 0)
                                                {
                                                    offset = "col-sm-offset-6";
                                                    offset2 = "col-sm-offset-1";
                                                    alignment = "debits";
                                                }
                                                else
                                                {
                                                    offset = "";
                                                    offset2 = "";
                                                    alignment = "credits";
                                                }
                                                <div class="row timeline-movement">
                                                    <div class="timeline-badge">
                                                        <span class="timeline-balloon-date-day">@item.DateOfAction.Day</span>
                                                        <span class="timeline-balloon-date-month">@item.DateOfAction.ToString("MMM").ToUpper()</span>
                                                    </div>
                                                    <div class="@offset col-sm-6 timeline-item">
                                                        <div class="row">
                                                            <div class="@offset2 col-sm-11">
                                                                <div class="timeline-panel @alignment">
                                                                    <ul class="timeline-panel-ul">
                                                                        <li><span class="importo">Certificate Number: @item.Certificate.CertNo</span></li>
                                                                        <li><span class="causale">Date of Action: @item.DateOfAction</span></li>
                                                                        <li><span class="causale">Action Taken: @item.ActionTaken</span></li>
                                                                        <li><span class="causale">Action By: @item.User.FirstName @item.User.LastName</span></li>
                                                                        <li><p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> @item.DateOfAction.ToLongDateString()</small></p> </li>
                                                                    </ul>
                                                                </div>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                i++;
                                            }
                                        }
                                    </div>
                                    <!--due -->
                                </div>
                                                }
                                            }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>