ecims/ecims/ViewModels/SmsTestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ecims.ViewModels
{
    public class SmsTestViewModel : BaseDashboardViewModel
    {
        public string PhoneNumber { get; set; }
        public string Message { get; set; }

    }
}

ecims/ecims/Controllers/SmsTestController.cs
using ecims.Models;
using ecims.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ecims.Controllers
{
    public class SmsTestController : Controller
    {
        ApplicationDbContext _context;
        private ApplicationUserManager _userManager;

        public SmsTestController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: SmsTest
        public ActionResult SmsTest(SmsTestViewModel model)
        {
            //Get ID of the currently logged in user
            var userId = User.Identity.GetUserId();
            //Create user object based off user ID
            var user = _context.Users.Where(u => u.Id == userId).Single();
            
            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            return View(new SmsTestViewModel
            {
                user = user,
                role = roles
            });
        }
        // POST: SmsTest
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendSms(SmsTestViewModel model)
        {
            //Get ID of the currently logged in user
            var userId = User.Identity.GetUserId();
            //Create user object based off user ID
            var user = _context.Users.Where(u => u.Id == userId).Single();
            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();

            //Send user verification SMS
            IdentityMessage SmsMessage = new IdentityMessage();
            //send accompanying SMS reminding user to verify their email
            string smsBody = model.Message;
            string phoneNumber = model.PhoneNumber;

            SmsMessage.Body = smsBody;
            SmsMessage.Destination = phoneNumber;
            SmsMessage.Subject = "Testing";
            
            //Send SMS
            SmsService smsSerice = new SmsService();
            await smsSerice.SendAsync(SmsMessage);



            return View(new SmsTestViewModel
            {
                user = user,
                role = roles
            });
        }
    }
}

ecims/ecims/Views/SmsTest/SmsTest.cshtml
@model ecims.ViewModels.SmsTestViewModel
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Dashboard.cshtml";
}

@using (Html.BeginForm("SendSms", "SmsTest", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    @class = "form-horizontal",
    role = "form",
    @id = "smsTestForm"
}))
{
    @Html.AntiForgeryToken()
    <div class="col-md-12">
        @Html.LabelFor(m => m.PhoneNumber, "Phone Number", new { @class = "" })
        @Html.TextAreaFor(m => m.PhoneNumber, new { @class = "form-control required-field" })
    </div>
    <div class="col-md-12">
        @Html.LabelFor(m => m.Message, "Message", new { @class = "" })
        @Html.TextAreaFor(m => m.Message, new { @class = "form-control required-field" })
    </div>
    <div class="form-group">
        <ul class="list-inline pull-right">
            <li><input type="submit" id="submit" class="btn btn-success" value="Submit" /></li>
        </ul>
    </div>
}